# Generated by Django 2.0.5 on 2018-06-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('Editable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_title', models.CharField(max_length=200)),
                ('Emails_title', models.CharField(max_length=100)),
                ('From_email', models.CharField(max_length=100)),
            ],
        ),
    ]
